apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql  
spec:  
  serviceName: mysql-h
  #podManagementPolicy: Parallel => cria as replicas em paralelo e não sequencial
  replicas: 3
  selector: 
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root 
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume

  volumeClaimTemplates: #Cria volume dinamicamente assim que criar uma nova replica. Nesse caso não precisa do persistent-volume-claim
  - metadata:
      name: mysql-volume
    spec: 
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
